#!/bin/bash

cd "`dirname "$0"`/../"
echo
echo
echo
echo "/!\\/!\\/!\\/!\\/!\\"
echo
echo
echo "Il faudra appuyer sur Ctrl + C pour quitter le serveur de debug"
echo
echo
echo "/!\\/!\\/!\\/!\\/!\\"
echo
echo
echo

jekyll
