#!/bin/bash
PATH=/usr/local/bin:/usr/local/Cellar/ruby/1.9.2-p180/bin/:$PATH

cd "`dirname "$0"`/../"
echo
echo
echo
echo "/!\\/!\\/!\\/!\\/!\\"
echo
echo
echo "Il faudra appuyer sur Ctrl + C pour quitter le serveur de debug"
echo
echo
echo "/!\\/!\\/!\\/!\\/!\\"
echo
echo
echo

jekyll
